### ISSUE TITLE
Hydra does not compile with CUDA 10.1

### ISSUE THREAD

**Issue by daisyron** [MultithreadCorner/Hydra#74]
Hi,

Trying to compile a fresh clone of Hydra, it turns out that it fails to compile while using CUDA 10.1 due to the deprecated CUDA SDK function cudaConfigureCall, which was depricated since CUDA 7.0.

The following compiler error is obtained:
triple_chevron_launcher.hpp(180): error: identifier "cudaConfigureCall" is undefined.

I'm using Linux Fedora 29 with gcc 8.3.1.

Is there a plan to migrate the code to the latest CUDA release?

Thanks,
Ron.

**Comment by AAAlvesJr** [comment]
Hi Ron, thanks for using Hydra, I am aware of this. Please switch to the branch ```update-thrust-dev```.  The code there compiles nicely. There is a pair of issues i m working on, before to commit it to master branch. Sorry for this inconvenience.

**Comment by daisyron** [comment]
Thanks I'll try it.

Regads,
Ron.

**Comment by daisyron** [comment]
Hi Antonio,

I tried to do what you suggested. I did in the Hydra directory:

$ git checkout -b update-thrust-dev

Ensuring that I'm on the right branch:

$ git status .

I've Got: 

On branch update-thrust-dev

Unfortunately I've got the same compilation issue... :-(

Here is a typical error:
hydra/detail/external/thrust/system/cuda/detail/bulk/detail/cuda_launcher/triple_chevron_launcher.hpp(127): error: identifier "cudaConfigureCall" is undefined

Am doing do something wrong?
Thanks,

Ron.

**Comment by AAAlvesJr** [comment]
Hi Ron, please make a new clone and do 
```
cd Hydra
git checkout update-thrust-dev
```
then so on...

the -b parameter you used is the problem. The git documentation states:

 _Specifying -b causes a new branch to be created as if git-branch(1) were called and then checked out..._

Cheers
A.A.

**Comment by daisyron** [comment]
Hi Antonio,

Thanks for your rapid response...

Now it compiles nicely...

Regards,

Ron.

**Comment by AAAlvesJr** [comment]
Good. I will close this issue.
Regards
